version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./.docker/postgres/:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: react-auth
