version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ../:/workspace:cached

  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    volumes:
      - ./.docker/postgres/:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: react-auth
